# Generated by Django 4.2.14 on 2024-08-08 10:22

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_make', models.CharField(max_length=40)),
                ('plane_model', models.CharField(max_length=20)),
                ('livery', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['plane_make'],
            },
        ),
        migrations.CreateModel(
            name='Gram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, unique=True)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('date_photographed', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('love', models.ManyToManyField(related_name='loved_grams', to=settings.AUTH_USER_MODEL)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gram_posts', to=settings.AUTH_USER_MODEL)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.aircraft')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('decision', models.IntegerField(choices=[(0, 'Awaiting'), (1, 'Accepted')], default=0)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('gram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.gram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
    ]
