# Generated by Django 4.2.14 on 2024-08-16 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='livery',
        ),
        migrations.AlterField(
            model_name='gram',
            name='love',
            field=models.ManyToManyField(blank=True, related_name='loved_grams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='decision',
            field=models.IntegerField(choices=[(0, 'Awaiting'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('gram', 'user')},
        ),
    ]
