# Generated by Django 4.2.14 on 2024-08-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_aircraft_livery_alter_gram_love_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='plane_model',
            field=models.CharField(max_length=40),
        ),
    ]
